# Generated by Django 5.2.6 on 2025-09-15 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_seance', models.CharField(max_length=100)),
                ('duree', models.PositiveIntegerField(help_text='Durée en minutes')),
                ('notes', models.TextField(blank=True, null=True)),
                ('cheval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='training.horse')),
            ],
        ),
    ]
