# Generated by Django 5.2.6 on 2025-09-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_horse_proprietaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='cout',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Coût de l'entraînement en euros", max_digits=7, null=True),
        ),
    ]
