# Generated by Django 5.2.6 on 2025-09-24 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_trainingsession_cout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='age',
        ),
        migrations.AddField(
            model_name='horse',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
