name: Deploy Django to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        run: |
          python manage.py test --settings=la_mulerie_training.settings.prod

      - name: Check secrets
        run: |
          if [ -z "${{ secrets.SERVER_HOST }}" ]; then
            echo "SERVER_HOST is missing!"
            exit 1
          else
            echo "SERVER_HOST is set"
          fi

          if [ -z "${{ secrets.SERVER_USER }}" ]; then
            echo "SERVER_USER is missing!"
            exit 1
          else
            echo "SERVER_USER is set"
          fi

          if [ -z "${{ secrets.SERVER_SSH_KEY }}" ]; then
            echo "SERVER_SSH_KEY is missing!"
            exit 1
          else
            echo "SERVER_SSH_KEY is set"
          fi


      - name: Deploy to VPS via SSH
        if: success()  # ne se lance que si les tests passent
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/la_mulerie_training
          
            chmod +x deploy.sh
            ./deploy.sh
 